<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        $content = "Chăm chỉ với công việc, không mắc tệ nạn xã hội";
        DB::table('category')->insert([
            'title' => 'Kế toán',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Kiểm toán',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Thương mại điện tử',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Tài chính ngân hàng',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Quản trị kinh doanh',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Kinh tế tài chính',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Vận tải',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Mỏ',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Địa chất',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Kĩ thuật điện',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Điện tử viễn thông',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Điều khiển tự động hóa',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert([
            'title' => 'Kiến trúc',
            'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Quay phim',
           'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Công nghệ thông tin',
           'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Trắc địa',
           'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Bảo vệ',
           'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Nhân viên bán hàng',
           'created_at' => new DateTime(),]);
        DB::table('category')->insert(['title' => 'Diễn viên đóng thế',
           'created_at' => new DateTime(),]);
        DB::table('users')->insert(
            [
                'id'=>'1',
                'username' => 'tatdat',
                'email' => 'tatdat97dhbkhn@gmail.com',
                'password' => bcrypt('123456'),
                'fullname'=>'Phạm Tất Đạt',
                'congty'=>'FPT',
                'dienthoai'=>'0981036562',
                'diachi'=>'Nam Định - Việt Nam',
                'quyen'=>'1',
                'nghe'=>'Đa nghề nghiệp',
                'created_at' => new DateTime(),
            ]);
        DB::table('users')->insert([
            'id'=>'2',
            'username' => 'linhdt',
            'email' => '20155347@hust.edu.vn',
            'password' => bcrypt('123456'),
            'fullname'=>'Dương Trọng Linh',
            'congty'=>'Xây dựng Trọng Linh',
            'dienthoai'=>'0981777222',
            'diachi'=>'Bắc Ninh - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Đa nghề nghiệp',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'3',
            'username' => 'hanguyen',
            'email' => 'hanguyen@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Nguyễn Thị Hà',
            'congty'=>'Xuân Thành',
            'dienthoai'=>'09724445566',
            'diachi'=>'Ninh Bình - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Công nghệ thông tin',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'4',
            'username' => 'ABC1',
            'email' => 'ABC1@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Tôi là ABC',
            'congty'=>'Framgia1',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Luật sư',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'5',
            'username' => 'ABC2',
            'email' => 'ABC2@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Tôi là ABC2',
            'congty'=>'Framgia2',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Bảo vệ',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'6',
            'username' => 'ABC1',
            'email' => 'ABC3@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Tôi là ABC3',
            'congty'=>'Framgia3',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Trắc địa',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'7',
            'username' => 'ABC4',
            'email' => 'ABC4@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Tôi là ABC',
            'congty'=>'Framgia4',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Quay phim',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'8',
            'username' => 'ABC5',
            'email' => 'ABC5@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Tôi là ABC5',
            'congty'=>'Framgia5',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'1',
            'nghe'=>'Kiến trúc',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'9',
            'username' => 'adminDat',
            'email' => 'admin@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Phạm Tất Đạt',
            'congty'=>'Topica',
            'dienthoai'=>'2222444441',
            'diachi'=>'Hà Nội - Việt Nam',
            'quyen'=>'2',
            'nghe'=>'Công nghệ thông tin',
            'created_at' => new DateTime(),
        ]);
        DB::table('users')->insert([
            'id'=>'10',
            'username' => 'TatDat',
            'email' => 'phamtatdat241197@gmail.com',
            'password' => bcrypt('123456'),
            'fullname'=>'Phạm Tất Đạt',
            'quyen'=>'0',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_1.jpg',
            'category_id'=>'1',
            'created_at'=>new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_2.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_3.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_4.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_5.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'01_6.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'02.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'02_1.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_10.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_1.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'1',
            'title'=>'Tuyển nhân viên',
            'description'=>'FPT',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_2.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_3.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_4.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_5.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_6.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_7.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_8.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_9.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_GS-Nhung.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_land.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert( [
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1a.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'2',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xây dựng Trọng Linh',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1DSC_0032.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_land.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1_H1_resize.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'1ha-van-tham.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_2.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_3.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_4.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_5.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_6.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'3',
            'title'=>'Tuyển nhân viên',
            'description'=>'Xuân Thành',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_7.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_8.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_9.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2_valentines.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2GS-Ngo.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'2kegietnguoi.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert( [
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'3.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'3_1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'300.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"FULL TIME",
            'sogio'=>'60h',
            'Hinh'=>'34.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_2.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'4',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia1',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_3.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_benmosche.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_coin.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_ec1.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_Econ2-popup.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_egypt.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_somali.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3D-1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'4.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400480.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'5',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia2',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400_1.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x180.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x250.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x259.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x280.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x300.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x322.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x350.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'400x400.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'430.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'4553697.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'6',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia3',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'490.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'4_1.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'4_2.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'5.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'51.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'5_1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'5_2.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'3_1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'5_model.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'6.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'7.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'7',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia4',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'7_1.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'8.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'8_1.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'8_2.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'8_3.jpg',
            'category_id'=>'1',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'9.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'9_1.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'TCNH',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'a01.jpg',
            'category_id'=>'4',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'a11.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert( [
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'TMDT',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'a111.jpg',
            'category_id'=>'3',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'a16.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('post')->insert([
            'user_id'=>'8',
            'title'=>'Tuyển nhân viên',
            'description'=>'Framgia5',
            'content'=>$content,
            'keywork'=>'KT2',
            'thoigian'=>"PART TIME",
            'sogio'=>'70',
            'Hinh'=>'a1_1.jpg',
            'category_id'=>'2',
            'created_at' => new DateTime(),
        ]);
        DB::table('cv')->insert([
            'users_id'=>'10',
            'fullname'=>'Phạm Tất Đạt',
            'gender'=>'Nam',
            'email'=>'phamtatdat241197@gmail.com',
            'phone'=>'0981036562',
            'birthday'=>'1997-11-24',
            'Hinh'=>'tatdat.jpg',
            'job_position'=>'KT2',
            'information'=>'Đẹp trai, chăm chỉ với công việc',
            'education'=>'Đại học Bách Khoa Hà Nội',
            'skill'=>'Thiết kế và lập trình web',
            'experience'=>'Chưa đi làm',
            'project'=>'project',
            'status'=>'Đang đi học',
            'created_at'=>new DateTime(),
        ]);
    }
}
